version: '3.8'

services:
  db:
    image: postgres:14
    container_name: ray_pg
    restart: always
    environment:
      POSTGRES_USER: rayuser
      POSTGRES_PASSWORD: raypass
      POSTGRES_DB: raydb
    volumes:
      - pgdata:/var/lib/postgresql/data

  bot:
    build: .
    container_name: raybot
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://rayuser:raypass@db:5432/raydb
    volumes:
      - ./session:/usr/src/app/session

volumes:
  pgdata:
