services:
  - type: web
    name: ray-md-pairing
    env: node
    buildCommand: npm install
    startCommand: node index.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
